import { withNeutral } from '../../copy/neutral';
import { fridayIntros, jesterRoasts, nationIntros, seasonEchoes, streakTemplates } from '../../copy/templates';
import type { Theme } from '../theme-types';

/** Ursprungstemat: svenskt medeltidsrike. Färgerna speglar :root i globals.css. */
export const realm: Theme = {
  key: 'realm',
  appName: 'Rundpingisriket',
  tagline: 'Tronen, riddarna och kröningarna i kontorets pingisrike.',
  nav: {
    home: 'Tronsalen',
    leaderboard: 'Rikets främsta',
    history: 'Krönikan',
    players: 'Riddare',
    badges: 'Utmärkelser',
    archive: 'Arkivet',
    settings: 'Rådet',
  },
  pages: {
    home: { title: 'Tronsalen', subtitle: 'Vem härskar över riket — och vem vågar utmana?' },
    leaderboard: { title: 'Rikets främsta', subtitle: 'Rankat efter total tid på tronen.' },
    history: { title: 'Historik', subtitle: 'De senaste 50 händelserna i riket.' },
    players: { title: 'Riddare', subtitle: 'Rikets utmanare. Klicka in på en riddare för full profil.' },
    badges: { title: 'Utmärkelser', subtitle: 'Alla {count} bragder en riddare kan förtjäna i riket.' },
    archive: { title: 'Arkivet', subtitle: 'Säsongerna som varit — och den som pågår.' },
    settings: { title: 'Rådet', subtitle: 'Miljöstatus för integrationer.' },
  },
  notFound: { title: 'Denna sal finns inte', subtitle: 'Kartan över riket har inget rum med det namnet. Kanske har härolden skrivit fel.', back: 'Tillbaka till Tronsalen' },
  epithets: { rank1: 'Kejsaren', rank2: 'Kronprinsen', rank3: 'Rikets tredje kraft' },
  roles: { monarch: 'Kung', monarchLower: 'kung', challenger: 'Utmanare', player: 'riddare', players: 'Riddare' },
  verbs: { crown: 'Kröna', crowning: 'kröning', crowningNow: 'Kröner…' },
  coronation: {
    sound: 'fanfare',
    crier: 'Hör upp! 🔔',
    decree: 'har tagit det som är deras — med racket och eld 🗡️🔥',
    holdCrier: 'Tronen håller stånd ❄️🐉',
    holdDecree: 'försvarar tronen — {streak} i rad. Mother of Aces. 🥚🔥🏓',
    dismiss: 'Länge leve regenten →',
    jester: '🃏',
    streakCreature: '🐉',
    roasts: jesterRoasts,
  },
  badgeOverrides: {},
  announcements: withNeutral({ streakTemplates, nationIntros, fridayIntros, seasonEchoes }),
  seasonWord: 'Säsong',
  nationLabel: 'Rikets läge',
  nationStates: {
    STABLE_ERA: { name: 'Fredens tid', emoji: '🕊️', blurb: 'Lugnet vilar över riket. Ingen har utmanat på allvar.' },
    TENSION: { name: 'Oro i riket', emoji: '⚠️', blurb: 'Flera har smakat på kronan den senaste tiden. Folket mumlar på torget.' },
    INSTABILITY: { name: 'Tronstrider', emoji: '🌀', blurb: 'Kronan byter huvud oftare än hovet byter kläder.' },
    DYNASTY: { name: 'Dynasti', emoji: '🏰', blurb: 'Tre raka eller fler. Murarna kring tronen växer.' },
    TYRANNY: { name: 'Tyranni', emoji: '👁️', blurb: 'Fem raka eller fler. Oppositionen sitter i tornet.' },
    REVOLUTION: { name: 'Revolution', emoji: '🔥', blurb: 'En dynasti har just störtats. Allt är möjligt igen.' },
  },
  progressTemplate: '{current} av {target} {unit}',
  colors: {
    bg: '#120d08',
    panel: '#1e1810',
    panelSoft: '#271f15',
    text: '#f1e3c6',
    muted: '#b29a72',
    accent: '#c9a227',
    accent2: '#8a2b22',
    border: '#4b3a1f',
    gold: '#e7c25c',
  },
};
