import { withNeutral } from '../../copy/neutral';
import { fridayIntros, jesterRoasts, nationIntros, seasonEchoes, streakTemplates } from '../../copy/templates';
import type { Theme } from '../theme-types';

/** Ursprungstemat: svenskt medeltidsrike. Färgerna speglar :root i globals.css. */
export const realm: Theme = {
  key: 'realm',
  appName: 'Rundpingisriket',
  tagline: 'Tronen, riddarna och kröningarna i kontorets pingisrike.',
  nav: {
    home: 'Tronsalen',
    leaderboard: 'Rikets främsta',
    history: 'Krönikan',
    players: 'Riddare',
    badges: 'Utmärkelser',
    archive: 'Arkivet',
    settings: 'Rådet',
  },
  pages: {
    home: { title: 'Tronsalen', subtitle: 'Vem härskar över riket — och vem vågar utmana?' },
    leaderboard: { title: 'Rikets främsta', subtitle: 'Rankat efter total tid på tronen.' },
    history: { title: 'Historik', subtitle: 'Säsongens händelser i riket, senaste först.' },
    players: { title: 'Riddare', subtitle: 'Rikets utmanare. Klicka in på en riddare för full profil.' },
    badges: { title: 'Utmärkelser', subtitle: 'Alla {count} bragder en riddare kan förtjäna i riket.' },
    archive: { title: 'Arkivet', subtitle: 'Säsongerna som varit — och den som pågår.' },
    settings: { title: 'Rådet', subtitle: 'Miljöstatus för integrationer.' },
  },
  notFound: { title: 'Denna sal finns inte', subtitle: 'Kartan över riket har inget rum med det namnet. Kanske har härolden skrivit fel.', back: 'Tillbaka till Tronsalen' },
  epithets: { rank1: 'Kejsaren', rank2: 'Kronprinsen', rank3: 'Rikets tredje kraft' },
  roles: { monarch: 'Kung', monarchLower: 'kung', challenger: 'Utmanare', player: 'riddare', players: 'Riddare' },
  verbs: { crown: 'Kröna', crowning: 'kröning', crowningNow: 'Kröner…' },
  coronation: {
    sound: 'fanfare',
    crier: 'Hör upp! 🔔',
    decree: 'har tagit det som är deras — med racket och eld 🗡️🔥',
    holdCrier: 'Tronen håller stånd ❄️🐉',
    holdDecree: 'försvarar tronen — {streak} i rad. Mother of Aces. 🥚🔥🏓',
    dismiss: 'Länge leve regenten →',
    jester: '🃏',
    streakCreature: '🐉',
    roasts: jesterRoasts,
  },
  badgeOverrides: {},
  announcements: withNeutral({ streakTemplates, nationIntros, fridayIntros, seasonEchoes }),
  seasonWord: 'Säsong',
  nationLabel: 'Rikets läge',
  nationStates: {
    STABLE_ERA: { name: 'Fredens tid', emoji: '🕊️', blurb: 'Lugnet vilar över riket. Ingen har utmanat på allvar.' },
    TENSION: { name: 'Oro i riket', emoji: '⚠️', blurb: 'Flera har smakat på kronan den senaste tiden. Folket mumlar på torget.' },
    INSTABILITY: { name: 'Tronstrider', emoji: '🌀', blurb: 'Kronan byter huvud oftare än hovet byter kläder.' },
    DYNASTY: { name: 'Dynasti', emoji: '🏰', blurb: 'Tre raka eller fler. Murarna kring tronen växer.' },
    TYRANNY: { name: 'Tyranni', emoji: '👁️', blurb: 'Fem raka eller fler. Oppositionen sitter i tornet.' },
    REVOLUTION: { name: 'Revolution', emoji: '🔥', blurb: 'En dynasti har just störtats. Allt är möjligt igen.' },
  },
  progressTemplate: '{current} av {target} {unit}',
  profile: {
    addTitle: 'Dubba en ny riddare',
    addSubtitle: 'Lägg till en ny spelare i riket.',
    addPlaceholder: 'Namnge en ny riddare…',
    addButton: 'Dubba riddare',
    addBusy: 'Dubbar…',
    addDuplicate: 'En riddare med det namnet finns redan.',
    viewProfile: 'Visa profil →',
    back: '← Tillbaka till riddarna',
    reigning: 'Regerar just nu',
    resting: 'Vilar från tronen — men vakten är uppe',
    never: 'Har ännu inte bestigit tronen',
    quoteKing: 'Historien skrivs fortfarande.',
    quoteFriday: 'Fredagarna fruktar detta namn.',
    quoteFormer: 'En gång kung. Alltid farlig.',
    quoteNever: 'Denna riddare väntar fortfarande på sin första krona.',
    rankTitle: 'Rikets rang',
    rankSubtitle: 'Var spelaren står mot alla andra i riket.',
    rankTop: ['Bäst i riket', 'Tvåa i riket', 'Trea i riket'],
    timelineTitle: 'Kungakrönika',
    timelineSubtitle: 'Spelarens väg genom riket, senaste först.',
    timelineEmpty: 'Ingen historik ännu — krönikan väntar på sitt första kapitel.',
    events: {
      NEW_KING: 'Ny kung krönt', FIRST_WIN: 'Första vinsten', SAME_KING_STREAK_2: 'Försvarade tronen (x2)', SAME_KING_STREAK_3: 'Dynasti byggs (x3)',
      SAME_KING_STREAK_4: 'Järngrepp (x4)', SAME_KING_STREAK_5_PLUS: 'Tyranni (x5+)', STREAK_BREAK_SMALL: 'Bröt en liten streak', STREAK_BREAK_MEDIUM: 'Bröt en streak',
      STREAK_BREAK_MAJOR: 'Störtade en dynasti', STREAK_BREAK_LEGENDARY: 'Legendariskt störtande', COMEBACK: 'Comeback', FRIDAY_FINAL: 'Fredagsfinal', RECORD_BROKEN: 'Rekord slaget',
    },
    feudTitle: '⚔️ Ärkefiende',
    feudEmpty: 'Ingen rival ännu. Byt kronan fram och tillbaka med någon så uppstår en fejd.',
    feudTaken: 'kronor du snott',
    feudLost: 'kronor snodda från dig',
    feudLead: 'Övertaget är ditt — för nu.',
    feudBehind: 'Rivalen har övertaget. Hämnden väntar.',
    feudTie: 'Dödläge. Varje krona är ett krig.',
  },
  heraldry: {
    sigilWord: 'Vapensköld',
    vesselWord: 'Skepp',
    hull: 'sail',
    vessels: [{ name: 'Eka' }, { name: 'Kogg' }, { name: 'Galeas' }, { name: 'Karack' }, { name: 'Drakskepp' }, { name: 'Regalskepp' }],
  },
  colors: {
    bg: '#120d08',
    panel: '#1e1810',
    panelSoft: '#271f15',
    text: '#f1e3c6',
    muted: '#b29a72',
    accent: '#c9a227',
    accent2: '#8a2b22',
    border: '#4b3a1f',
    gold: '#e7c25c',
  },
};
