import type { Theme } from '../theme-types';

/**
 * Galaktiskt tema. Visar vad temalagret klarar: samma logik, helt annat rike.
 * Endast badges vars namn är uttalat medeltida döps om — resten ärvs.
 */
export const starWars: Theme = {
  key: 'star-wars',
  appName: 'Rundpingisgalaxen',
  tagline: 'Tronen, riddarna och upphöjelserna i kontorets pingisgalax.',
  nav: {
    home: 'Tronrummet',
    leaderboard: 'Galaxens främsta',
    history: 'Arkiven',
    players: 'Jediriddare',
    badges: 'Utmärkelser',
    archive: 'Tidsvalvet',
    settings: 'Rådet',
  },
  pages: {
    home: { title: 'Tronrummet', subtitle: 'Vem härskar över galaxen — och vem vågar utmana?' },
    leaderboard: { title: 'Galaxens främsta', subtitle: 'Rankat efter total tid på tronen.' },
    history: { title: 'Arkiven', subtitle: 'De senaste 50 händelserna i galaxen.' },
    players: { title: 'Jediriddare', subtitle: 'Galaxens utmanare. Klicka in på en riddare för full profil.' },
    badges: { title: 'Utmärkelser', subtitle: 'Alla {count} bragder en jedi kan förtjäna i galaxen.' },
    archive: { title: 'Tidsvalvet', subtitle: 'Säsongerna som varit — och den som pågår.' },
    settings: { title: 'Rådet', subtitle: 'Miljöstatus för integrationer.' },
  },
  epithets: { rank1: 'Kejsaren', rank2: 'Lärlingen', rank3: 'Galaxens tredje kraft' },
  roles: { monarch: 'Mästare', monarchLower: 'mästare', challenger: 'Utmanare', player: 'jedi', players: 'Jediriddare' },
  verbs: { crown: 'Upphöj', crowning: 'upphöjelse' },
  badgeOverrides: {
    current_king: { name: 'Nuvarande mästare', emoji: '🌟', description: 'Sitter just nu på tronen.' },
    emperor: { name: 'Kejsaren', emoji: '⚡', description: 'Mest total tid på tronen.' },
    crown_collector: { name: 'Kristallsamlaren', emoji: '💠', description: 'Flest totala vinster.' },
    dynasty_founder: { name: 'Ordensgrundaren', emoji: '🏛️', description: 'Har nått minst 3 raka vinster.' },
    hr_case: { name: 'Rådet är oroat', emoji: '🚨', description: 'Har nått minst 4 raka vinster. Situationen övervakas.' },
    tyrant: { name: 'Sithlorden', emoji: '🔴', description: 'Har nått minst 5 raka vinster.' },
    state_owned: { name: 'Imperiet', emoji: '🛰️', description: 'Har gjort bordet till en lydstat under sitt styre.' },
    defender_of_the_throne: { name: 'Tronvakten', emoji: '🛡️', description: 'Har vunnit medan de redan satt på tronen.' },
    tyrant_slayer: { name: 'Sithdräparen', emoji: '⚔️', description: 'Har brutit en streak på 5+ vinster.' },
    revolutionary: { name: 'Rebellen', emoji: '🔥', description: 'Har avslutat en dynasti på 3+ raka vinster.' },
    king_slayer: { name: 'Mästarmördaren', emoji: '🗡️', description: 'Flest takeover-vinster mot sittande mästare.' },
    regime_changer: { name: 'Upprorsledaren', emoji: '🩸', description: 'Har brutit flest streaks.' },
    longest_reign: { name: 'Holokronen', emoji: '📜', description: 'Har haft den längsta enskilda regeringstiden.' },
    prophecy: { name: 'Den utvalde', emoji: '✨', description: 'Återvände till tronen när galaxen minst anade det.' },
    lost_heir: { name: 'Den förlorade lärlingen', emoji: '🫥', description: 'Har historisk relevans men har varit borta länge.' },
    time_traveler: { name: 'Återkomsten', emoji: '🕰️', description: 'Vann igen efter ett mycket långt uppehåll.' },
    borrowed_crown: { name: 'Kronan var lånad', emoji: '🤡', description: 'Har flera korta regeringstider.' },
    eagle_has_landed: { name: 'Falken har landat', emoji: '🦅', description: 'Ingen vet exakt vad detta betyder. Men det har hänt.' },
  },
  announcements: {
    streakTemplates: {
      NEW_KING: ['🌟 @{winner} har bestigit tronen.', '⚡ Makten har skiftat. @{winner} härskar nu.'],
      SAME_KING_STREAK_2: ['🛡️ @{winner} försvarar tronen. Två i rad.'],
      SAME_KING_STREAK_3: ['🏛️ @{winner} bygger en orden. Tre raka.'],
      SAME_KING_STREAK_4: ['🚨 Fyra raka. Rådet håller @{winner} under uppsikt.'],
      SAME_KING_STREAK_5_PLUS: ['🔴 @{winner} har gått över till den mörka sidan. Fem i rad.'],
      STREAK_BREAK_SMALL: ['💥 @{winner} bröt @{previousKing}s svit.'],
      STREAK_BREAK_MEDIUM: ['🔥 Upproret lyckades. @{winner} störtade @{previousKing}.'],
      STREAK_BREAK_MAJOR: ['⚔️ @{previousKing}s välde på {previousStreakCount} föll för @{winner}.'],
      STREAK_BREAK_LEGENDARY: ['🌌 Balans i kraften. @{winner} fällde @{previousKing} efter {previousStreakCount} raka.'],
      FIRST_WIN: ['✨ @{winner} tar sin första seger. En ny kraft väcks.'],
      COMEBACK: ['🕰️ Efter {days} dagar i exil är @{winner} tillbaka.'],
    },
    nationIntros: {
      STABLE_ERA: ['Galaxen vilar.'],
      TENSION: ['Oro sprider sig i yttre randen.'],
      INSTABILITY: ['Senaten är i upplösning.'],
      DYNASTY: ['En orden reser sig.'],
      TYRANNY: ['Imperiet härskar.'],
      REVOLUTION: ['Rebellalliansen slår tillbaka.'],
    },
    fridayIntros: ['⚔️ FREDAGENS DUELL ÄR AVGJORD.', '🍻 Fredag, högsta insats — galaxen skälver.'],
  },
  colors: {
    bg: '#05070f',
    panel: '#0e1424',
    panelSoft: '#151d31',
    text: '#dbe6f5',
    muted: '#7f90ad',
    accent: '#4ea1e0',
    accent2: '#c2334d',
    border: '#26334d',
    gold: '#ffd84a',
  },
};
