import { galaxyFridayIntros, galaxyJesterRoasts, galaxyNationIntros, galaxySeasonEchoes, galaxyStreakTemplates } from '../../copy/galaxy';
import { withNeutral } from '../../copy/neutral';
import type { Theme } from '../theme-types';

/**
 * Galaktiskt tema. Visar vad temalagret klarar: samma logik, helt annat rike.
 * Endast badges vars namn är uttalat medeltida döps om — resten ärvs.
 */
export const starWars: Theme = {
  key: 'star-wars',
  appName: 'Rundpingisgalaxen',
  tagline: 'Tronen, riddarna och upphöjelserna i kontorets pingisgalax.',
  nav: {
    home: 'Tronrummet',
    leaderboard: 'Galaxens främsta',
    history: 'Arkiven',
    players: 'Jediriddare',
    badges: 'Utmärkelser',
    archive: 'Tidsvalvet',
    settings: 'Rådet',
  },
  pages: {
    home: { title: 'Tronrummet', subtitle: 'Vem härskar över galaxen — och vem vågar utmana?' },
    leaderboard: { title: 'Galaxens främsta', subtitle: 'Rankat efter total tid på tronen.' },
    history: { title: 'Arkiven', subtitle: 'De senaste 50 händelserna i galaxen.' },
    players: { title: 'Jediriddare', subtitle: 'Galaxens utmanare. Klicka in på en riddare för full profil.' },
    badges: { title: 'Utmärkelser', subtitle: 'Alla {count} bragder en jedi kan förtjäna i galaxen.' },
    archive: { title: 'Tidsvalvet', subtitle: 'Säsongerna som varit — och den som pågår.' },
    settings: { title: 'Rådet', subtitle: 'Miljöstatus för integrationer.' },
  },
  notFound: { title: 'Det här är inte sidan du letar efter', subtitle: 'Koordinaterna leder rakt ut i tomrummet. Hyperrymden har inga rum med det namnet.', back: 'Tillbaka till Tronrummet' },
  epithets: { rank1: 'Kejsaren', rank2: 'Lärlingen', rank3: 'Galaxens tredje kraft' },
  roles: { monarch: 'Mästare', monarchLower: 'mästare', challenger: 'Utmanare', player: 'jedi', players: 'Jediriddare' },
  verbs: { crown: 'Upphöj', crowning: 'upphöjelse', crowningNow: 'Upphöjer…' },
  coronation: {
    crier: 'Kraften har talat ✨',
    decree: 'har tagit tronrummet — med racket och ljussabel ⚔️✨',
    holdCrier: 'Sköldarna håller 🛡️🛰️',
    holdDecree: 'försvarar tronrummet — {streak} i rad. Kraften är stark i denna. ✨🏓',
    dismiss: 'Må kraften vara med er →',
    jester: '🤖',
    streakCreature: '🛸',
    roasts: galaxyJesterRoasts,
  },
  badgeOverrides: {
    current_king: { name: 'Nuvarande mästare', emoji: '🌟', description: 'Sitter just nu på tronen.' },
    emperor: { name: 'Darth Vader', emoji: '🖤', icon: '/badges/darth-vader.png', description: 'Mest total tid på tronen. Galaxen lyder.' },
    crown_collector: { name: 'Kristallsamlaren', emoji: '💠', description: 'Flest totala vinster.' },
    dynasty_founder: { name: 'Ordensgrundaren', emoji: '🏛️', description: 'Har nått minst 3 raka vinster.' },
    hr_case: { name: 'Rådet är oroat', emoji: '🚨', description: 'Har nått minst 4 raka vinster. Situationen övervakas.' },
    tyrant: { name: 'Sithlorden', emoji: '🔴', description: 'Har nått minst 5 raka vinster.' },
    state_owned: { name: 'Imperiet', emoji: '🛰️', description: 'Har gjort bordet till en lydstat under sitt styre.' },
    defender_of_the_throne: { name: 'Tronvakten', emoji: '🛡️', description: 'Har vunnit medan de redan satt på tronen.' },
    tyrant_slayer: { name: 'Sithdräparen', emoji: '⚔️', description: 'Har brutit en streak på 5+ vinster.' },
    revolutionary: { name: 'Rebellen', emoji: '🔥', description: 'Har avslutat en dynasti på 3+ raka vinster.' },
    king_slayer: { name: 'Mästarmördaren', emoji: '🗡️', description: 'Flest takeover-vinster mot sittande mästare.' },
    regime_changer: { name: 'Upprorsledaren', emoji: '🩸', description: 'Har brutit flest streaks.' },
    longest_reign: { name: 'Holokronen', emoji: '📜', description: 'Har haft den längsta enskilda regeringstiden.' },
    prophecy: { name: 'Den utvalde', emoji: '✨', description: 'Återvände till tronen när galaxen minst anade det.' },
    lost_heir: { name: 'Den förlorade lärlingen', emoji: '🫥', description: 'Har historisk relevans men har varit borta länge.' },
    time_traveler: { name: 'Återkomsten', emoji: '🕰️', description: 'Vann igen efter ett mycket långt uppehåll.' },
    borrowed_crown: { name: 'Kronan var lånad', emoji: '🤡', description: 'Har flera korta regeringstider.' },
    eagle_has_landed: { name: 'Falken har landat', emoji: '🦅', description: 'Ingen vet exakt vad detta betyder. Men det har hänt.' },
    efficient_monarch: { name: 'Effektiv kejsare', emoji: '🎯', description: 'Högst tron-tid per vinst.' },
    friday_champion: { name: 'Kantinamästaren', emoji: '🍺', description: 'Flest fredagsvinster i galaxen.' },
    prime_time_player: { name: 'Holonet-stjärnan', emoji: '📡', description: 'Har vunnit flera fredagsfinaler.' },
    after_work_assassin: { name: 'Sköt först', emoji: '🔫', description: 'Är oproportionerligt farlig på fredagar. Fråga inte vem som sköt först.' },
    recent_champion: { name: 'Stigande stjärna', emoji: '🌠', description: 'Flest vinster senaste 30 dagarna.' },
    steep_curve: { name: 'Kraften växer', emoji: '🧗', description: 'Störst procentuell ökning av vinster sedan förra säsongen.' },
    hot_right_now: { name: 'Kraften är stark', emoji: '✨', description: 'Har starkast form just nu.' },
    momentum: { name: 'Hyperfart', emoji: '🚀', description: 'Har vunnit flera gånger den senaste veckan.' },
    cold: { name: 'Hoth-kall', emoji: '🥶', description: 'Har inte vunnit på 14+ dagar. Kallt som på Hoth.' },
    frozen: { name: 'Karbonfryst', emoji: '🧊', description: 'Har inte vunnit på 30+ dagar. Jabba är nöjd.' },
    historically_relevant: { name: 'En gammal religion', emoji: '🪦', description: 'Toppspelare historiskt, men svag nutida form.' },
    chaos_agent: { name: 'Prisjägaren', emoji: '🎯', description: 'Är ofta inblandad i tronskiften — på båda sidor.' },
    short_reign_specialist: { name: 'Senator för en dag', emoji: '🏛️', description: 'Har ovanligt kort genomsnittlig regeringstid.' },
    people_favorite: { name: 'Rebellernas favorit', emoji: '🎭', description: 'Vinner ofta, men bygger sällan ordnar.' },
    statistically_unlikely: { name: 'Säg aldrig oddsen', emoji: '📊', description: 'Har lyckats vinna trots svag historik.' },
    five_crowns: { name: 'Fem kristaller', emoji: '🖐️', description: 'Har vunnit fem gånger.' },
    ten_crowns: { name: 'Tio kristaller', emoji: '🔟', description: 'Tio segrar i galaxen.' },
    twentyfive_crowns: { name: 'Kristallernas kvartssekel', emoji: '🏅', description: 'Tjugofem segrar. Nu är det en karriär.' },
    fifty_crowns: { name: 'Halvsekelkejsaren', emoji: '🎖️', description: 'Femtio segrar. Bordet borde döpas om.' },
    week_on_throne: { name: 'En vecka i tronrummet', emoji: '📅', description: 'Har suttit en hel vecka i ett svep.' },
    month_on_throne: { name: 'Månadens kejsare', emoji: '🗓️', description: 'Trettio dagar utan att bli störtad.' },
    monday_monarch: { name: 'Måndagsmästaren', emoji: '🌧️', description: 'Minst tre måndagsvinster. Börjar veckan med att härska.' },
    season_opener: { name: 'Galaxens förste', emoji: '🎬', description: 'Tog säsongens allra första krona.' },
    eternal_second: { name: 'Den evige lärlingen', emoji: '🥈', description: 'Näst mest trontid. Så nära, så länge.' },
    usurper: { name: 'Tronrövaren', emoji: '🗡️', description: 'Har tagit kronan från minst fem olika mästare.' },
  },
  announcements: withNeutral({ streakTemplates: galaxyStreakTemplates, nationIntros: galaxyNationIntros, fridayIntros: galaxyFridayIntros, seasonEchoes: galaxySeasonEchoes }),
  backdrop: 'starfield',
  historyStyle: 'crawl',
  colors: {
    bg: '#05070f',
    panel: '#0e1424',
    panelSoft: '#151d31',
    text: '#dbe6f5',
    muted: '#7f90ad',
    accent: '#4ea1e0',
    accent2: '#c2334d',
    border: '#26334d',
    gold: '#ffd84a',
  },
};
