import type { BadgeDefinition } from './badge-types';

export const BADGES = [
  { id: 'current_king', name: 'Nuvarande kung', emoji: '👑', description: 'Sitter just nu på tronen.', rarity: 'rare', category: 'throne', tone: 'prestige' },
  { id: 'emperor', name: 'Kejsaren', emoji: '👑', description: 'Mest total tid på tronen all-time.', rarity: 'legendary', category: 'throne', tone: 'prestige' },
  { id: 'crown_collector', name: 'Kronsamlaren', emoji: '💎', description: 'Flest totala vinster.', rarity: 'epic', category: 'throne', tone: 'prestige' },
  { id: 'efficient_monarch', name: 'Effektiv monark', emoji: '🎯', description: 'Högst tron-tid per vinst.', rarity: 'epic', category: 'meta', tone: 'prestige' },
  { id: 'longest_reign', name: 'Historieboken', emoji: '📜', description: 'Har haft den längsta enskilda regeringstiden.', rarity: 'legendary', category: 'legacy', tone: 'prestige' },
  { id: 'dynasty_founder', name: 'Dynastigrundaren', emoji: '🏛️', description: 'Har nått minst 3 raka vinster.', rarity: 'epic', category: 'streak', tone: 'dramatic', ladder: 'longest_streak', tier: 1 },
  { id: 'hr_case', name: 'HR-ärende', emoji: '🚨', description: 'Har nått minst 4 raka vinster. Situationen är under uppsikt.', rarity: 'epic', category: 'streak', tone: 'meme', ladder: 'longest_streak', tier: 2 },
  { id: 'tyrant', name: 'Tyrann', emoji: '☢️', description: 'Har nått minst 5 raka vinster.', rarity: 'legendary', category: 'streak', tone: 'dramatic', ladder: 'longest_streak', tier: 3 },
  { id: 'state_owned', name: 'Statligt ägd', emoji: '🏴', description: 'Har gjort bordet till administrativ enhet under sitt styre.', rarity: 'legendary', category: 'streak', tone: 'meme', ladder: 'longest_streak', tier: 4 },
  { id: 'defender_of_the_throne', name: 'Tronsförsvararen', emoji: '🛡️', description: 'Har vunnit medan de redan satt på tronen.', rarity: 'rare', category: 'streak', tone: 'prestige' },
  { id: 'friday_champion', name: 'Fredagsmästaren', emoji: '🏟️', description: 'Flest fredagsvinster i riket.', rarity: 'epic', category: 'friday', tone: 'prestige' },
  { id: 'prime_time_player', name: 'Prime Time Player', emoji: '📺', description: 'Har vunnit flera fredagsfinaler.', rarity: 'rare', category: 'friday', tone: 'prestige' },
  { id: 'after_work_assassin', name: 'After Work Assassin', emoji: '🍻', description: 'Är oproportionerligt farlig på fredagar.', rarity: 'rare', category: 'friday', tone: 'meme' },
  { id: 'best_when_it_counts', name: 'Bäst när det gäller', emoji: '💪', description: 'Fredag är den veckodag där flest av de egna vinsterna kommit.', rarity: 'rare', category: 'friday', tone: 'prestige' },
  { id: 'recent_champion', name: 'Nylig mästare', emoji: '📈', description: 'Flest vinster senaste 30 dagarna.', rarity: 'epic', category: 'form', tone: 'prestige' },
  { id: 'steep_curve', name: 'Hög utvecklingskurva', emoji: '🧗', description: 'Störst procentuell ökning av vinster jämfört med förra säsongen.', rarity: 'epic', category: 'form', tone: 'prestige' },
  { id: 'hot_right_now', name: 'Het just nu', emoji: '🔥', description: 'Har starkast form just nu.', rarity: 'rare', category: 'form', tone: 'prestige', ladder: 'recent_form', tier: 1 },
  { id: 'momentum', name: 'Momentum', emoji: '⚡', description: 'Har vunnit flera gånger den senaste veckan.', rarity: 'rare', category: 'form', tone: 'prestige', ladder: 'recent_form', tier: 2 },
  { id: 'cold', name: 'Kylig', emoji: '🧊', description: 'Har inte vunnit på 14+ dagar.', rarity: 'common', category: 'form', tone: 'roast', ladder: 'inactivity', tier: 1 },
  { id: 'frozen', name: 'Nedfryst', emoji: '❄️', description: 'Har inte vunnit på 30+ dagar.', rarity: 'rare', category: 'form', tone: 'roast', ladder: 'inactivity', tier: 2 },
  { id: 'lost_heir', name: 'Den förlorade arvingen', emoji: '🫥', description: 'Har historisk relevans men har varit borta från tronen länge.', rarity: 'epic', category: 'legacy', tone: 'roast', ladder: 'inactivity', tier: 3 },
  { id: 'historically_relevant', name: 'Historiskt relevant', emoji: '🪦', description: 'Toppspelare historiskt, men svag nutida form.', rarity: 'epic', category: 'legacy', tone: 'roast', ladder: 'inactivity', tier: 4 },
  { id: 'tyrant_slayer', name: 'Tyrannfällaren', emoji: '⚔️', description: 'Har brutit en streak på 5+ vinster.', rarity: 'legendary', category: 'combat', tone: 'dramatic', ladder: 'streaks_broken', tier: 2 },
  { id: 'regime_changer', name: 'Regimskiftare', emoji: '🩸', description: 'Har brutit flest streaks.', rarity: 'epic', category: 'combat', tone: 'dramatic' },
  { id: 'king_slayer', name: 'Kungamördaren', emoji: '🪓', description: 'Flest takeover-vinster mot sittande kungar.', rarity: 'epic', category: 'combat', tone: 'dramatic' },
  { id: 'revolutionary', name: 'Revolutionären', emoji: '🔥', description: 'Har avslutat en dynasti på 3+ raka vinster.', rarity: 'epic', category: 'combat', tone: 'dramatic', ladder: 'streaks_broken', tier: 1 },
  { id: 'chaos_agent', name: 'Kaosagenten', emoji: '🌀', description: 'Är ofta inblandad i tronskiften.', rarity: 'rare', category: 'chaos', tone: 'meme' },
  { id: 'borrowed_crown', name: 'Kronan var lånad', emoji: '🤡', description: 'Har flera korta regeringstider.', rarity: 'common', category: 'shame', tone: 'roast', ladder: 'short_reign', tier: 2 },
  { id: 'short_reign_specialist', name: 'Kort mandatperiod', emoji: '🐌', description: 'Har ovanligt kort genomsnittlig regeringstid.', rarity: 'common', category: 'shame', tone: 'roast', ladder: 'short_reign', tier: 1 },
  { id: 'people_favorite', name: 'Folkets favorit', emoji: '🎭', description: 'Vinner ofta, men bygger sällan dynastier.', rarity: 'rare', category: 'meta', tone: 'meme' },
  { id: 'statistically_unlikely', name: 'Statistiskt osannolik', emoji: '📊', description: 'Har lyckats vinna trots svag historik.', rarity: 'rare', category: 'meta', tone: 'meme' },
  { id: 'time_traveler', name: 'Tidsresenären', emoji: '🕰️', description: 'Vann igen efter ett mycket långt uppehåll.', rarity: 'epic', category: 'legacy', tone: 'dramatic' },
  { id: 'prophecy', name: 'Profetian', emoji: '📜', description: 'Återvände till tronen när riket minst anade det.', rarity: 'mythical', category: 'legacy', tone: 'dramatic' },
  { id: 'eagle_has_landed', name: 'Örnen har landat', emoji: '🦅', description: 'Ingen vet exakt vad detta betyder. Men det har hänt.', rarity: 'mythical', category: 'chaos', tone: 'meme' },
  // Antal kronor — en trappa med fasta mål, till skillnad från Kronsamlaren som är relativ.
  { id: 'five_crowns', name: 'Fem kronor', emoji: '🖐️', description: 'Har vunnit fem gånger.', rarity: 'common', category: 'throne', tone: 'prestige', ladder: 'wins_count', tier: 1 },
  { id: 'ten_crowns', name: 'Tio kronor', emoji: '🔟', description: 'Tio segrar i riket.', rarity: 'rare', category: 'throne', tone: 'prestige', ladder: 'wins_count', tier: 2 },
  { id: 'twentyfive_crowns', name: 'Kronornas kvartssekel', emoji: '🏅', description: 'Tjugofem segrar. Nu är det en karriär.', rarity: 'epic', category: 'throne', tone: 'prestige', ladder: 'wins_count', tier: 3 },
  { id: 'fifty_crowns', name: 'Halvsekelkungen', emoji: '🎖️', description: 'Femtio segrar. Bordet borde döpas om.', rarity: 'legendary', category: 'throne', tone: 'prestige', ladder: 'wins_count', tier: 4 },
  // Längd på en enskild regering.
  { id: 'week_on_throne', name: 'En vecka på tronen', emoji: '📅', description: 'Har suttit en hel vecka i ett svep.', rarity: 'rare', category: 'throne', tone: 'prestige', ladder: 'reign_length', tier: 1 },
  { id: 'month_on_throne', name: 'Månadens härskare', emoji: '🗓️', description: 'Trettio dagar utan att bli störtad.', rarity: 'legendary', category: 'throne', tone: 'prestige', ladder: 'reign_length', tier: 2 },
  // Kalendern: när på veckan och dygnet man vinner.
  { id: 'monday_monarch', name: 'Måndagsmonarken', emoji: '🌧️', description: 'Minst tre måndagsvinster. Börjar veckan med att härska.', rarity: 'rare', category: 'calendar', tone: 'meme' },
  { id: 'early_bird', name: 'Morgonrodnad', emoji: '🌅', description: 'Har vunnit före klockan tio. Kaffet hann inte ens svalna.', rarity: 'common', category: 'calendar', tone: 'meme' },
  { id: 'lunch_warrior', name: 'Lunchkrigaren', emoji: '🥪', description: 'Minst tre vinster mitt i lunchen.', rarity: 'rare', category: 'calendar', tone: 'meme' },
  { id: 'overtime', name: 'Övertid', emoji: '🌙', description: 'Vinner efter fem, när alla andra gått hem.', rarity: 'rare', category: 'calendar', tone: 'meme' },
  { id: 'all_weather', name: 'Allvädersspelaren', emoji: '🌦️', description: 'Har vunnit på veckans alla fem arbetsdagar.', rarity: 'epic', category: 'calendar', tone: 'prestige' },
  { id: 'hat_trick', name: 'Hattricket', emoji: '🎩', description: 'Tre vinster på en och samma dag.', rarity: 'epic', category: 'form', tone: 'dramatic' },
  { id: 'friday_phobia', name: 'Fredagsfobi', emoji: '🙈', description: 'Många vinster — men aldrig på en fredag.', rarity: 'common', category: 'shame', tone: 'roast', ladder: 'friday_avoidance', tier: 1 },
  { id: 'worst_when_it_counts', name: 'Sämst när det gäller', emoji: '🫠', description: 'Har vunnit måndag, tisdag, onsdag och torsdag — men aldrig på en fredag.', rarity: 'rare', category: 'shame', tone: 'roast', ladder: 'friday_avoidance', tier: 2 },
  // Arv, meta och strid.
  { id: 'season_opener', name: 'Rikets förste', emoji: '🎬', description: 'Tog säsongens allra första krona.', rarity: 'epic', category: 'legacy', tone: 'prestige' },
  { id: 'jar_jar', name: 'Jar Jar Binks', emoji: '🦎', icon: '/badges/jar-jar.png', description: 'Exsqueeze me! Meesa trodde det var meesa tur nu. How wude!', rarity: 'epic', category: 'shame', tone: 'roast' },
  { id: 'eternal_second', name: 'Den evige tvåan', emoji: '🥈', description: 'Näst mest trontid. Så nära, så länge.', rarity: 'rare', category: 'shame', tone: 'roast' },
  { id: 'steady_hand', name: 'Stadig hand', emoji: '🧱', description: 'Minst tre regeringar med ett dygn i snitt.', rarity: 'rare', category: 'meta', tone: 'prestige' },
  { id: 'boomerang', name: 'Bumerangen', emoji: '🪃', description: 'Störtad minst tre gånger — och tagit tillbaka kronan varje gång.', rarity: 'rare', category: 'chaos', tone: 'meme' },
  { id: 'usurper', name: 'Usurpatorn', emoji: '🗡️', description: 'Har tagit kronan från minst fem olika kungar.', rarity: 'epic', category: 'combat', tone: 'dramatic' },
] as const satisfies readonly BadgeDefinition[];

export const BADGE_BY_ID = Object.fromEntries(BADGES.map((b) => [b.id, b]));
