export type BadgeRarity = 'common' | 'rare' | 'epic' | 'legendary' | 'mythical';
export type BadgeCategory = 'throne' | 'streak' | 'friday' | 'form' | 'combat' | 'chaos' | 'shame' | 'legacy' | 'meta';
export type BadgeTone = 'prestige' | 'dramatic' | 'roast' | 'meme' | 'neutral';
export type BadgeDefinition = { id: string; name: string; emoji: string; description: string; rarity: BadgeRarity; category: BadgeCategory; tone: BadgeTone };
export type BadgeId = string;
export type PlayerStats = { playerId: string; totalWins: number; totalReignMs: number; longestReignMs: number; currentReignMs: number; currentStreak: number; longestStreak: number; fridayWins: number; winsLast30Days: number; winsLast7Days: number; daysSinceLastWin: number | null; streaksBroken: number; biggestStreakBroken: number; takeoverWins: number; timesDethroned: number; averageReignMs: number; crownEfficiencyMsPerWin: number; isCurrentKing: boolean };
export type GlobalStats = { maxTotalReignMs: number; maxTotalWins: number; maxLongestStreak: number; maxFridayWins: number; maxWinsLast30Days: number; maxStreaksBroken: number; maxBiggestStreakBroken: number; maxCrownEfficiencyMsPerWin: number; currentKingId: string | null };
export type PlayerBadgeContext = { now?: Date; playerStats: Record<string, PlayerStats>; globalStats: GlobalStats };
export type ComputedPlayerBadge = { id: BadgeId; definition: BadgeDefinition; reason: string; value?: number | string };
