import { EventType, NationState } from '@prisma/client';
import { isFriday } from 'date-fns';
import { prisma } from '@/lib/prisma';
import { fridayIntros, nationIntros, streakTemplates } from '@/lib/copy/templates';

export async function getCurrentKing() { return prisma.reign.findFirst({ where:{ endedAt:null }, include:{ player:true }, orderBy:{ startedAt:'desc' } }); }
export function determineEventType(ctx:{isSameKing:boolean; streakCount:number; previousStreakCount?:number|null;}):EventType {
 if (ctx.isSameKing) return ctx.streakCount===2?EventType.SAME_KING_STREAK_2:ctx.streakCount===3?EventType.SAME_KING_STREAK_3:ctx.streakCount===4?EventType.SAME_KING_STREAK_4:EventType.SAME_KING_STREAK_5_PLUS;
 const p=ctx.previousStreakCount??0; if(p>=5)return EventType.STREAK_BREAK_LEGENDARY; if(p===4)return EventType.STREAK_BREAK_MAJOR; if(p===3)return EventType.STREAK_BREAK_MEDIUM; if(p===2)return EventType.STREAK_BREAK_SMALL; return EventType.NEW_KING;
}
export function determineNationState(ctx:{recentWinnerIds:string[]; currentStreak:number; brokeBigStreak:boolean;}):NationState { if(ctx.currentStreak>=5)return NationState.TYRANNY; if(ctx.currentStreak>=3)return NationState.DYNASTY; if(ctx.brokeBigStreak)return NationState.REVOLUTION; const u=new Set(ctx.recentWinnerIds).size; if(u>=5)return NationState.INSTABILITY; if(u>=3)return NationState.TENSION; return NationState.STABLE_ERA; }
export function generateAnnouncement(ctx:any){ const templ=(streakTemplates as any)[ctx.eventType]?.[0] ?? `👑 @{winner} har krönts.`; let text=templ.replaceAll('@{winner}',ctx.winnerName).replaceAll('@{previousKing}',ctx.previousKingName??'Ingen').replaceAll('{previousStreakCount}',String(ctx.previousStreakCount??0)); if(Math.random()>0.4) text=`${nationIntros[ctx.nationState as keyof typeof nationIntros][0]}\n${text}`; if(ctx.isFridayFinal) text=`${fridayIntros[0]}\n${text}`; return { text, layout:'royal', persona:'ROYAL_DECREE' }; }
export async function calculateStreak(winnerId:string){ const events=await prisma.winEvent.findMany({where:{winnerId}, orderBy:{occurredAt:'desc'}, take:10}); return events.length===0?0:events.reduce((acc,e,i)=> i===0?1: acc + (events[i-1].occurredAt>=e.occurredAt?1:0),0); }
export async function recordWin(winnerId:string,note?:string){ const now=new Date(); const current=await getCurrentKing(); const isSameKing=current?.playerId===winnerId; const previousEvents=await prisma.winEvent.findMany({orderBy:{occurredAt:'desc'},take:7}); const previousStreakCount=previousEvents[0]?.streakCount ?? 0; const streakCount=isSameKing?previousStreakCount+1:1; const eventType=determineEventType({isSameKing:!!isSameKing, streakCount, previousStreakCount}); const nationState=determineNationState({recentWinnerIds:previousEvents.map(e=>e.winnerId),currentStreak:streakCount,brokeBigStreak:!isSameKing&&previousStreakCount>=3}); const winner=await prisma.player.findUniqueOrThrow({where:{id:winnerId}}); const ann=generateAnnouncement({eventType,winnerName:winner.name,previousKingName:current?.player.name,previousStreakCount,nationState,isFridayFinal:isFriday(now)});
 return prisma.$transaction(async(tx)=>{ if(current && !isSameKing){ await tx.reign.update({where:{id:current.id}, data:{endedAt:now}}); await tx.reign.create({data:{playerId:winnerId,startedAt:now}});} if(!current){ await tx.reign.create({data:{playerId:winnerId,startedAt:now}});} const win=await tx.winEvent.create({data:{winnerId,previousKingId:current?.playerId,occurredAt:now,eventType,streakCount,previousStreakCount,note,announcementText:ann.text,nationState,isFridayFinal:isFriday(now)}}); const a=await tx.announcement.create({data:{winEventId:win.id,text:ann.text,layout:ann.layout,persona:ann.persona}}); return {win,a}; }); }
export async function calculateLeaderboard(){ const players=await prisma.player.findMany({include:{wins:true,reigns:true}}); return players.map(p=>({id:p.id,name:p.name,wins:p.wins.length,currentStreak:p.wins.at(-1)?.streakCount??0,longestStreak:Math.max(0,...p.wins.map(w=>w.streakCount)),totalKingMs:p.reigns.reduce((s,r)=>s+((r.endedAt??new Date()).getTime()-r.startedAt.getTime()),0)})).sort((a,b)=>b.totalKingMs-a.totalKingMs); }
